# Generated by Django 5.0 on 2023-12-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=False)),
                ("nome_produto", models.CharField(max_length=100)),
                ("codigo_produto", models.IntegerField()),
                ("descricao_produto", models.CharField(max_length=100)),
                ("preco_produto", models.CharField(max_length=100)),
            ],
        ),
    ]
