# Generated by Django 5.0 on 2023-12-16 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nunesapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Produtos",
            new_name="Produto",
        ),
    ]
